### ISSUE TITLE
add docker

### ISSUE THREAD

**Issue by MathieuMoalic** [seeder-research/uMagNUS#15]
Hello,
Nice work on this project, it's really impressive all that you have done. 
I'm quite novice when it comes to OpenGL and C bindings but do you think it would be possible to add Docker to the build process to make it easier and more reproducible to build on different hardware ?

**Comment by seeder-research** [comment]
Hi Mathieu,
We use Docker but are not proficient at making container recipes for Dockerbuilds. Will attempt to create one as you request. We have experience building on Singularity/Apptainer so maybe that will help. Our containers are based off the same template so we will need to recreate the whole process on Docker.

**Comment by MathieuMoalic** [comment]
In the past few months I started modifying my personal version of mumax ( mostly frontend / data formats / convenience functions / etc. ) and I found that using Docker simplified this process quite a lot as it can output a "somewhat" portable binary to use both on our worstations and on HPC. Now, if you have an already existing container solution more appropriate than docker, then you can dismiss my request, it's just that I only know docker at the moment and I was interested in this project as it is active, unlike the original mumax project.

**Comment by xfong** [comment]
dockerfile is available in v2.2.1
