### ISSUE TITLE
Installation on Windows- bad image error (with OpenCL.lib)

### ISSUE THREAD

**Issue by jplauzie** [seeder-research/uMagNUS#21]
Hello,

I'm currently trying to run the provided binary for Windows 10. It is currently given a bad image error, related to OpenCL.lib:

![umagnusimage](https://user-images.githubusercontent.com/108704520/177892542-0a10d76b-c061-4cd6-9368-6073d4be0a5e.jpg)

This is running Windows 10 (64 bit), Cuda 11.3 (511.79 on nvidia-smi), with C:\cuda\, C:\cuda\bin and C:\cuda\lib\x64 all in PATH. It's an Nvidia 1070 ti GPU.

Similarly, when I try to build it using msys2 (I have built mumax before, so following a similar installation/procedure, just using the TDM gcc compiler), it also runs into an issue with OpenCL.lib. It says it can't find it. This seems unlikely, because I just rebuilt mumax3, and OpenCL.lib is located in the same path/folder as stuff like curand.lib

![umagnus2](https://user-images.githubusercontent.com/108704520/177893458-00d92409-9b3c-49b7-ae39-0a790b35b255.jpg)

Is there some additional step that needs to be done? 

My go environment for msys2 is this:
![umagnus3](https://user-images.githubusercontent.com/108704520/177906346-f2ad2a02-3b02-4a66-9299-57414bb280e7.jpg)

**Comment by seeder-research** [comment]
Thank you for trying the code.

For the binary to run, try adding the directory with OpenCL.dll to your PATH environment variable. On my Windows 11 PC, the path is C:\Windows\SysWOW64. This should be the case on your Windows 10 machine. OpenCL.lib is used only for compilation and linking. OpenCL.dll is needed for running. You can take a look at this to check whether your OpenCL setup on Windows works: https://streamhpc.com/blog/2015-03-16/how-to-install-opencl-on-windows/

If you want to have a simple binary to test your environment, you can download clinfo from GitHub (https://github.com/Oblomov/clinfo) and compile on msys.

**Comment by seeder-research** [comment]
One more point to note. When compiling in MSYS2, if GCC is v10 and above, do not use TDM. Make sure your PATH points only to the default toolchain in MSYS2.

**Comment by jplauzie** [comment]
For compiling:

I did switch back to the native gcc compiler for MSYS2. (I should also mention, MSYS2 did not seem to come with a default "make" command in the base installation. I ended up installing this version of make: [mingw-w64-x86_64-make](https://packages.msys2.org/package/mingw-w64-x86_64-make?repo=mingw64). I'm fairly sure they're largely interchangeable, but if it's a concern, I can try reinstalling. Looking at Msys2, there is supposed to be a base make command [mingw-w64-make](https://packages.msys2.org/base/mingw-w64-make), but for some reason it gave "bash : make: command not found" by default on my installation. Probably I can find it and add it to my Windows PATH if need be),


Going into cl/stubs and running "make all" works, and generates an OpenCL.lib without any errors.

I went back to the main directory, and tried to run "make all" there (in the previous comment, I had only done "go install -v while in 'github.com\seeder-research\uMagNUS\cmd\uMagNUS' directory). Initially, running the full makefile runs into the same type of error with -lOpenCL . I attached the full error.txt ([compile1.txt](https://github.com/seeder-research/uMagNUS/files/9082329/compile1.txt)), but the relevant snippet is:

![compile1](https://user-images.githubusercontent.com/108704520/178213528-22df86c8-d81c-4bde-94b7-54b0282b1d60.jpg)

It doesn't give the full detail. Running "make all" in the 'cl-compiler' folder gives the error about -lOpenCL.lib, so presumably that is the issue. Adding export CGO_LDFLAGS="-L<path to OpenCL.lib>". clears that error
 up, and the makefile is able to proceed further. However, it gets a similar error (
[lumagnus.txt](https://github.com/seeder-research/uMagNUS/files/9082332/lumagnus.txt)
), looking for -lumagnus:
![umagnuslibmissing](https://user-images.githubusercontent.com/108704520/178217356-927562dc-e88f-4673-8485-0309721d22e9.jpg)


I assume (I am not at all sure, so my attempted fix might not make sense) this means it's looking for a umagnus.lib or umagnus.dll. I did not see a .lib, so I tried to pointing it to the umagnus.dll located in \uMagNUS\cl_loader\lib since that seems to be the only instance. So if the previous flag was CGO_LDFLAGS="-L C:\cuda\lib\x64", it seemed to have 2 paths you just need a space (I am not sure on this, I've done some but not much linking with C/C++). So it becomes export CGO_LDFLAGS="-L C:\cuda\lib\x64 C:\Go\src\github.com\seeder-research\uMagNUS\cl_loader\lib". The latter path containing a file called umagnus.dll . This causes a permission error:

![umagnus5(permission)](https://user-images.githubusercontent.com/108704520/178217141-986626d4-1f71-40cd-905e-d089f4dbcfb0.jpg)

I tried to get around this by making a copy of umagnus.dll (as well as umagnus64.dll), and placing them with OpenCL.lib (so I could use just the previously working export path). This generates a different error (
[kludge.txt](https://github.com/seeder-research/uMagNUS/files/9082335/kludge.txt)
). I'm not sure why, but I'm assuming it's because my kludge with the paths was not proper:

![compilehiddenincuda](https://user-images.githubusercontent.com/108704520/178219988-6b3f8be9-9842-4809-b35a-7f2007c6ff80.jpg)

--

For the other tools, I am still working on compiling them (it seems after Nvidia intially dropped support for OpenCL, so a lot of the links are deprecated). I was able to find a precompiled binary of clinfo however, and it runs. The output is [clinfo.txt](https://github.com/seeder-research/uMagNUS/files/9082338/clinfo.txt). So it seems to be fine. I've found a couple other tools that also recognize the card as running OpenCL 3.0 CUDA. And of course, the win11 precompiled binary worked, as I mentioned in the previous post. So I'm fairly confident the OpenCL installation itself is actually ok, it's just a matter of getting everything linked properly on windows (which is always a bit of a headache. I'm totally fine with just using the precompiled provided binaries if need be, I mainly tried compiling since the binary had an error)

**Comment by seeder-research** [comment]
Are you able to print your environment variables? The main ones I would like to know are:
GOPATH
PATH
CGO_LDFLAGS

I think msys2 has plain “make”. I recall searching and saw that there is one under msys2/make. This one is different from those with mingw.

The simplest way forward is to first get the precompiled binary to run. You will only need the correct PATH in this case. The umagnus.dll packaged with the binary is a blank library.

The difference with recompilation is that the opencl kernels are compiled so they get loaded instead of being recompiled every time uMagNUS is started. With the packaged dll, the binary will still run but it starts by compiling the kernels.

Best,
Xuanyao (Kelvin) Fong

**Comment by jplauzie** [comment]
Hi Kelvin,

What version of OpenCL did you use, for the Windows version, if it didn't come packaged with CUDA?

For the precompiled binary-
I tried removing OpenCL.lib from the path (until I got the error that it couldn't find it), and then added at the end of the path. I also tried removing it and adding it to the start of the path. They seem to give the same error. I also copied all the dll's (based on the ldd output) directly into the folder with the binary, but it still gives the issue.

If it's just an issue with the path, could that cause the different behavior between the win11 and win10 precompiled binaries? (Both the different ldd results, or the fact that the win11 version does run without that error). A path issue would make sense, except I would it to happen with both of them.

I think what might be happening is that the win10 version isn't linked to the dll properly (it doesn't show Opencl.dll at all on when i run ldd on it, whereas the win11 does), so it tries to use the lib to find the dll. The win11 is linked to the dll correctly, so no issue. But I don't have a lot of experience linking, so I'm not sure if that is plausible

I do have a clean machine I just got access to, so I'll give that a go and try to copy your process exactly.

**Comment by jplauzie** [comment]
For compiling-

I went ahead and reinstalled Msys2 from scratch, and 'make' is now working (I follow [this](https://www.msys2.org/) installation, which seems more complete). My current environment is GOPATH="C:\Go", GOROOT="C:\msys64\mingw64\lib\go". and CGO_LDFlags="-g -02". The full environment:
![goenv](https://user-images.githubusercontent.com/108704520/182016001-3073bafd-ae59-4c94-aaa4-421c090d6da2.jpg)



I am building within the GOPATH, $GOPATH/src/github.com/seeder-research/uMagNUS. I did set GOROOT and GOPATH myself, they were originally inherited from my old Go installation (even after uninstalling/reinstalling, Golang seems to preserve them). CGO_LDFlags should be the default value, I've never changed it.

In regards to the libraries, I think the reason I'm having to set CGO_LDFlags explicitly is that MSYS2 might not inherit my windows PATH properly (i set it by setting a variable in environment variables, MSYS2_PATH_TYPE=inherit). If i try to do for instance "find OpenCL.lib" or "which OpenCL.lib", it cannot find the file despite it being on the path. I'm not finding many workarounds to setting the path within MSYS2, beyond setting that variable

I did make progress after adding export CGO_LDFLAGS="-L C:\cuda\lib\x64 -L C:\Go\src\github.com\seeder-research\uMagNUS\cl_loader\lib". It is now getting stuck looking for 'k_threefry_seed_async" and similar variables in the RNGthreefry.go file: 
![error](https://user-images.githubusercontent.com/108704520/182015955-d3d795f2-1c03-4c41-bfd5-99b348a7ba14.jpg)


Thanks again for all your help!

Best,
Josh Lauzier

**Comment by xfong** [comment]
Hi Josh,

For my Win10 set up, you do not need to install anything special to have OpenCL. I believe it comes with the DirectX components of Win10. Based on my reading of your latest error, your build should compile and link correctly if you go to $GOPATH/src/github.com/seeder-research/uMagNUS and run `make realclean && make go.mod && make all` from there. You need to make sure your CGO_LDFLAGS is set to "-LC:\cuda\lib\x64 -L C:\Go\src\github.com\seeder-research\uMagNUS\cl_loader\lib" before calling the make commands.

**Comment by jplauzie** [comment]
Hi,

It worked, first try! :)

I did have to copy umagnus.dll (it was in the libmagnus folder) over after it built, but otherwise exactly what you said. I ran the executable through standard problem 4 with no issues.

I can't wait to give uMagNUS a proper run. Thanks for your patience, I know building on Windows can be a bit of pain

Cheers,
Josh

**Comment by xfong** [comment]
Perfect! I'll close the issue for now.
